"""empty message

Revision ID: 8950162b6e4b
Revises: 9392b1382a02
Create Date: 2017-12-10 21:32:02.211000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8950162b6e4b'
down_revision = '9392b1382a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'info', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_constraint(u'user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'info_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'user_ibfk_1', 'user', 'info', ['info_id'], ['id'])
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    op.drop_constraint(None, 'info', type_='foreignkey')
    op.drop_column('info', 'user_id')
    # ### end Alembic commands ###
