"""empty message

Revision ID: 9d779b2d9d2d
Revises: 69ceaf09ff5b
Create Date: 2018-01-13 12:37:08.742000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d779b2d9d2d'
down_revision = '69ceaf09ff5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sa.String(length=100), nullable=False))
    op.drop_column('category', 'cagory_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('cagory_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('category', 'category_name')
    # ### end Alembic commands ###
