"""empty message

Revision ID: e4498fba9bc1
Revises: a386baf08e65
Create Date: 2017-12-11 00:43:38.129000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4498fba9bc1'
down_revision = 'a386baf08e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_name', sa.String(length=100), nullable=True))
    op.drop_index('rolename', table_name='role')
    op.create_unique_constraint(None, 'role', ['role_name'])
    op.drop_column('role', 'rolename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('rolename', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_index('rolename', 'role', ['rolename'], unique=True)
    op.drop_column('role', 'role_name')
    # ### end Alembic commands ###
